# Root logger
log4j.rootLogger=INFO, Console, File

# Console Appender
log4j.appender.Console=org.apache.log4j.ConsoleAppender
log4j.appender.Console.layout=org.apache.log4j.PatternLayout
log4j.appender.Console.layout.ConversionPattern=%d{HH:mm:ss.SSS} [%t] %-5p %c{36} - %m%n

# Application Loggers
log4j.logger.com.example.orc=DEBUG
log4j.logger.org.apache.orc=INFO
log4j.logger.org.apache.hadoop=WARN