apiVersion: v1
kind: Service
metadata:
  name: fluss-coordinator-svc
spec:
  selector:
    app.kubernetes.io/component: coordinator
  ports:
    - port: 9124
      targetPort: 9124
      name: ui-9124
    - port: 9123
      targetPort: 9123
      name: ui-9123
  type: LoadBalancer