FROM flink:1.17.2-scala_2.12
COPY ./paimon-flink-1.17-1.4-SNAPSHOT.jar /opt/flink/lib/paimon-flink.jar
COPY ./paimon-flink-action-*.jar /opt/flink/lib/paimon-flink-action.jar
COPY ./flink-shaded-hadoop-2-uber-2.8.3-10.0.jar /opt/flink/lib/
# https://github.com/apache/flink-cdc/blob/master/docs/content/docs/connectors/pipeline-connectors/overview.md
COPY ./flink-sql-connector-*-cdc-*.jar /opt/flink/lib/
COPY ./mysql-connector-*.jar /opt/flink/lib/
COPY ./flink-conf.yaml /opt/flink/conf/
RUN  mkdir /opt/flink/plugins/s3-fs-hadoop
COPY ./flink-s3-fs-hadoop-1.17.2.jar /opt/flink/plugins/s3-fs-hadoop/


# docker build -t my-flink:1.17.2-scala_2.12-paimon -f Dockerfile_flink .